data:
  root_path: ./data/
  image_folder: ADEChallengeData2016
  dataset_name: ade20k
  num_classes: 150
  crop_size: 504
  base_size:
  - 2044
  - 504
  ratio_range:
  - 0.5
  - 2.0
  test_scale:
  - 2044
  - 504
  batch_size_per_replica: 2
  num_workers: 8
  pin_memory: true
segmentation:
  channels: 512
  pool_scales:
  - 1
  - 2
  - 3
  - 6
  dropout: 0.1
  use_aux_head: true
  aux_index: 2
  aux_channels: 256
  aux_loss_weight: 0.4
opt:
  iterations: 160000
  name: adamw
  clip_grad: 0.0
  weight_decay: 0.05
  lr:
    auto_lr_scaling: false
    base_lr: 0.0001
    base_lr_batch_size: 16
    warmup_iters: 1500
    warmup_ratio: 1.0e-06
    power: 1.0
    min_lr: 0.0
    backbone_lr_scale: 1.0
  use_bfloat16: true
  bias_decay: false
  norm_decay: false
  global_seed: 0
framework:
  name: segmentation
model:
  pretrained_weights: ./vit-h16-cls.pth.tar
  model_name: vit_huge
  patch_size: 14
  crop_size: 224
  use_masked_vit: true
  use_class_token: true
  out_layers:
  - 7
  - 15
  - 23
  - 31
  drop_path_rate: 0.1
  window_size: 0
  use_checkpoint: false
  freeze_backbone: false
resume:
  resume_path: null
logging:
  log_dir: logs/ade20k_upernet_vith14/
  log_step_freq: 50
  use_tensorboard: true
  use_csv: true
  log_stdout: true
  ckpt:
    save_latest: true
    save_best: true
    ckpt_iter_freq: 8000
  wandb:
    use_wandb: true
    project_name: FG-JEPA
    entity: shuns71
    run_name: ade20k_upernet_vith14
  eval:
    eval_iter_freq: 16000
    slide_stride: 341
